### ISSUE TITLE
Create initial attachment

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-scc-da#34]
Description

At minimum one initial attachment

**Comment by ocofaigh** [comment]
When new provider release (1.64.0) drops in a few days which allows us to do data lookup of profiles using a name, we will be updating the SCC module to take profile name and version in (instead of profile ID). Once that is implemented, I think we could then update the SCC DA to create an initial attachment. Since profile ID is different per region, its kind of hard to implement with the data lookup by name coming in 1.64.0
